name: Lint

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25.7.0
          cache: "npm"
          cache-dependency-path: packages/react-router/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: packages/react-router

      - name: Lint
        run: npm run lint
        working-directory: packages/react-router
